services:
  nats:
    image: nats:2
    container_name: nats-local
    command: ["-c", "/etc/nats/nats.conf"]
    volumes:
      - ./nats.conf:/etc/nats/nats.conf:ro
    ports:
      - "4222:4222"
      - "8222:8222"
      - "9222:9222"

  mongo:
    image: mongo:latest
    container_name: mongo-chat
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    volumes:
      - mongo_data:/data/db
    restart: unless-stopped

  lgtm:
    image: grafana/otel-lgtm:latest
    container_name: lgtm-chat-service
    ports:
      - "3001:3000"
      - "4317:4317"
      - "4318:4318"
    volumes:
      - lgtm-data:/data
    restart: unless-stopped

volumes:
  mongo_data:
  lgtm-data:
